# 🔢 Lab 3: NumPy — Numerical Computing in Python
### DATA.110 - Introduction to Python Programming for Machine Learning
---
**Objective:** Master NumPy arrays for efficient numerical computation — the backbone of data science and machine learning in Python.

**Topics Covered:**
- Creating and inspecting NumPy arrays
- Array indexing, slicing, and reshaping
- Array operations and broadcasting
- Mathematical and statistical functions
- Linear algebra basics
- Random number generation
- Practical data manipulation

In [1]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


## 1. Creating NumPy Arrays
NumPy arrays (`ndarray`) are faster and more memory-efficient than Python lists for numerical data.

In [2]:
# From Python lists
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("1D array:", arr_1d)
print("2D array:\n", arr_2d)
print("3D array shape:", arr_3d.shape)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array shape: (2, 2, 2)


In [3]:
# Array creation functions
print("zeros(3x4):\n", np.zeros((3, 4)))
print("\nones(2x3):\n", np.ones((2, 3)))
print("\nfull(3x3, 7):\n", np.full((3, 3), 7))
print("\neye(4):\n", np.eye(4))
print("\narange(0, 20, 3):", np.arange(0, 20, 3))
print("linspace(0, 1, 9):", np.linspace(0, 1, 9))

zeros(3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones(2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

full(3x3, 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

arange(0, 20, 3): [ 0  3  6  9 12 15 18]
linspace(0, 1, 9): [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [4]:
# Array attributes
arr = np.array([[1.5, 2.3, 3.7], [4.1, 5.8, 6.2]])
print("Array:\n", arr)
print("\nShape:   ", arr.shape)    # (rows, cols)
print("ndim:    ", arr.ndim)      # number of dimensions
print("size:    ", arr.size)      # total elements
print("dtype:   ", arr.dtype)     # element data type
print("itemsize:", arr.itemsize, "bytes")

Array:
 [[1.5 2.3 3.7]
 [4.1 5.8 6.2]]

Shape:    (2, 3)
ndim:     2
size:     6
dtype:    float64
itemsize: 8 bytes


## 2. Indexing and Slicing

In [5]:
# 1D indexing
a = np.array([10, 20, 30, 40, 50, 60, 70])
print("Array:", a)
print("a[0]    :", a[0])      # first
print("a[-1]   :", a[-1])     # last
print("a[2:5]  :", a[2:5])    # slice
print("a[::2]  :", a[::2])    # every 2nd
print("a[::-1] :", a[::-1])   # reversed

Array: [10 20 30 40 50 60 70]
a[0]    : 10
a[-1]   : 70
a[2:5]  : [30 40 50]
a[::2]  : [10 30 50 70]
a[::-1] : [70 60 50 40 30 20 10]


In [6]:
# 2D indexing
M = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
print("Matrix M:\n", M)
print("\nM[0, 0]   :", M[0, 0])          # top-left
print("M[2, -1]  :", M[2, -1])          # bottom-right
print("M[1, :]   :", M[1, :])           # row 1 (all cols)
print("M[:, 2]   :", M[:, 2])           # col 2 (all rows)
print("M[0:2, 1:3]:\n", M[0:2, 1:3])   # submatrix

Matrix M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

M[0, 0]   : 1
M[2, -1]  : 12
M[1, :]   : [5 6 7 8]
M[:, 2]   : [ 3  7 11]
M[0:2, 1:3]:
 [[2 3]
 [6 7]]


In [7]:
# Boolean (fancy) indexing
scores = np.array([72, 88, 65, 91, 54, 79, 95, 61, 83, 70])
print("Scores:", scores)

# Mask
passing = scores >= 70
print("Mask (>=70):", passing)
print("Passing scores:", scores[passing])
print("Failing scores:", scores[~passing])
print("Scores between 75 and 90:", scores[(scores >= 75) & (scores <= 90)])

Scores: [72 88 65 91 54 79 95 61 83 70]
Mask (>=70): [ True  True False  True False  True  True False  True  True]
Passing scores: [72 88 91 79 95 83 70]
Failing scores: [65 54 61]
Scores between 75 and 90: [88 79 83]


## 3. Reshaping and Stacking

In [8]:
a = np.arange(1, 13)  # [1, 2, ..., 12]
print("Original (1D):", a)

b = a.reshape(3, 4)
print("\nreshaped to (3,4):\n", b)

c = a.reshape(2, 2, 3)
print("\nreshaped to (2,2,3):\n", c)

print("\nFlatten:\n", b.flatten())
print("Ravel:  ", b.ravel())

# Transpose
print("\nOriginal shape:", b.shape)
print("Transposed shape:", b.T.shape)
print("Transposed:\n", b.T)

Original (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]

reshaped to (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

reshaped to (2,2,3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flatten:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel:   [ 1  2  3  4  5  6  7  8  9 10 11 12]

Original shape: (3, 4)
Transposed shape: (4, 3)
Transposed:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [9]:
# Stacking arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Vertical stack:\n", np.vstack([x, y]))
print("Horizontal stack:", np.hstack([x, y]))

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("\nStack along axis=0 (vertical):\n", np.concatenate([A, B], axis=0))
print("Stack along axis=1 (horizontal):\n", np.concatenate([A, B], axis=1))

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]

Stack along axis=0 (vertical):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stack along axis=1 (horizontal):
 [[1 2 5 6]
 [3 4 7 8]]


## 4. Array Operations and Broadcasting

In [10]:
# Element-wise operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a:", a)
print("b:", b)
print("a + b  :", a + b)
print("b - a  :", b - a)
print("a * b  :", a * b)
print("b / a  :", b / a)
print("a ** 2 :", a ** 2)

a: [1 2 3 4 5]
b: [10 20 30 40 50]
a + b  : [11 22 33 44 55]
b - a  : [ 9 18 27 36 45]
a * b  : [ 10  40  90 160 250]
b / a  : [10. 10. 10. 10. 10.]
a ** 2 : [ 1  4  9 16 25]


In [11]:
# Broadcasting — operations on arrays of different shapes
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
row_vec = np.array([1, 0, -1])

print("Matrix + scalar:\n", matrix + scalar)
print("\nMatrix + row vector (broadcasting):\n", matrix + row_vec)
print("\nMatrix * 2:\n", matrix * 2)

Matrix + scalar:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Matrix + row vector (broadcasting):
 [[2 2 2]
 [5 5 5]
 [8 8 8]]

Matrix * 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## 5. Mathematical and Statistical Functions

In [12]:
# Universal functions (ufuncs)
arr = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print("Angles (radians):", arr)
print("sin:", np.round(np.sin(arr), 4))
print("cos:", np.round(np.cos(arr), 4))

vals = np.array([1, np.e, np.e**2, 10, 100])
print("\nValues:", vals)
print("log (natural):", np.round(np.log(vals), 4))
print("log10:        ", np.round(np.log10(vals), 4))
print("sqrt:         ", np.round(np.sqrt(vals), 4))
print("exp([0,1,2])  :", np.exp([0, 1, 2]))

Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin: [0.     0.5    0.7071 0.866  1.    ]
cos: [1.     0.866  0.7071 0.5    0.    ]

Values: [  1.           2.71828183   7.3890561   10.         100.        ]
log (natural): [0.     1.     2.     2.3026 4.6052]
log10:         [0.     0.4343 0.8686 1.     2.    ]
sqrt:          [ 1.      1.6487  2.7183  3.1623 10.    ]
exp([0,1,2])  : [1.         2.71828183 7.3890561 ]


In [13]:
# Statistical functions
np.random.seed(42)
data = np.random.randint(50, 100, size=(5, 6))
print("Data (5 students, 6 exams):\n", data)

print("\n--- Overall Statistics ---")
print(f"Mean:    {np.mean(data):.2f}")
print(f"Median:  {np.median(data):.2f}")
print(f"Std Dev: {np.std(data):.2f}")
print(f"Variance:{np.var(data):.2f}")
print(f"Min:     {np.min(data)}")
print(f"Max:     {np.max(data)}")

print("\n--- Per Student (row-wise mean) ---")
student_means = np.mean(data, axis=1)
for i, avg in enumerate(student_means, 1):
    print(f"  Student {i}: {avg:.2f}")

print("\n--- Per Exam (column-wise mean) ---")
exam_means = np.mean(data, axis=0)
for i, avg in enumerate(exam_means, 1):
    print(f"  Exam {i}: {avg:.2f}")

Data (5 students, 6 exams):
 [[88 78 64 92 57 70]
 [88 68 72 60 60 73]
 [85 89 73 52 71 51]
 [73 93 79 87 51 70]
 [82 61 71 93 74 98]]

--- Overall Statistics ---
Mean:    74.10
Median:  73.00
Std Dev: 13.19
Variance:173.96
Min:     51
Max:     98

--- Per Student (row-wise mean) ---
  Student 1: 74.83
  Student 2: 70.17
  Student 3: 70.17
  Student 4: 75.50
  Student 5: 79.83

--- Per Exam (column-wise mean) ---
  Exam 1: 83.20
  Exam 2: 77.80
  Exam 3: 71.80
  Exam 4: 76.80
  Exam 5: 62.60
  Exam 6: 72.40


## 6. Linear Algebra

In [14]:
A = np.array([[2, 1], [5, 3]])
B = np.array([[1, 0], [2, 4]])

print("A:\n", A)
print("B:\n", B)

# Matrix multiplication
print("\nA @ B (matrix multiply):\n", A @ B)
print("np.dot(A, B):\n", np.dot(A, B))

# Determinant and inverse
print("\ndet(A):", np.linalg.det(A))
A_inv = np.linalg.inv(A)
print("A inverse:\n", A_inv)
print("A @ A_inv (should be identity):\n", np.round(A @ A_inv))

# Eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:", eigenvalues)

# Solve linear system Ax = b
b = np.array([4, 7])
x = np.linalg.solve(A, b)
print("\nSolve Ax = b where b =», b)
print("Solution x:", x)
print("Verification A @ x:", A @ x)

SyntaxError: unterminated string literal (detected at line 24) (2369671896.py, line 24)

## 7. Random Number Generation

In [ ]:
np.random.seed(0)  # for reproducibility

# Different distributions
uniform = np.random.uniform(0, 1, 5)
normal  = np.random.normal(loc=0, scale=1, size=5)    # mean=0, std=1
integers = np.random.randint(1, 101, size=10)          # integers 1-100
binomial = np.random.binomial(n=10, p=0.5, size=8)    # coin flips

print("Uniform [0,1]:   ", np.round(uniform, 4))
print("Normal (0,1):    ", np.round(normal, 4))
print("Random integers: ", integers)
print("Binomial(n=10,p=0.5):", binomial)

# Random choice and shuffle
items = ['A', 'B', 'C', 'D', 'E']
print("\nRandom choice (3):  ", np.random.choice(items, size=3, replace=False))
arr = np.arange(1, 11)
np.random.shuffle(arr)
print("Shuffled [1..10]:   ", arr)

## 8. Practical Example: Student Performance Analysis

In [ ]:
np.random.seed(42)

# Simulate exam scores for 30 students across 5 exams
n_students = 30
n_exams = 5

raw_scores = np.random.normal(loc=75, scale=12, size=(n_students, n_exams))
scores = np.clip(raw_scores, 0, 100).astype(int)

print(f"Score matrix: {scores.shape} ({n_students} students × {n_exams} exams)")
print("First 5 rows:\n", scores[:5])

# Per-student averages
student_avg = scores.mean(axis=1)

# Grade assignment using np.where
grades = np.select(
    [student_avg >= 90, student_avg >= 80, student_avg >= 70, student_avg >= 60],
    ['A', 'B', 'C', 'D'],
    default='F'
)

# Grade distribution
unique_grades, counts = np.unique(grades, return_counts=True)
print("\nGrade Distribution:")
for g, c in zip(unique_grades, counts):
    bar = '█' * c
    print(f"  {g}: {bar} ({c} students)")

print(f"\nClass Statistics:")
print(f"  Mean:    {student_avg.mean():.2f}")
print(f"  Median:  {np.median(student_avg):.2f}")
print(f"  Std Dev: {student_avg.std():.2f}")
print(f"  Min:     {student_avg.min():.2f}")
print(f"  Max:     {student_avg.max():.2f}")

# Top 3 students
top3_idx = np.argsort(student_avg)[-3:][::-1]
print("\nTop 3 Students:")
for rank, idx in enumerate(top3_idx, 1):
    print(f"  #{rank} Student {idx+1}: avg={student_avg[idx]:.2f}, grade={grades[idx]}")

## 9. NumPy vs Python List — Speed Comparison

In [ ]:
import time

N = 1_000_000

# Python list
py_list = list(range(N))
t0 = time.time()
py_result = [x**2 for x in py_list]
t_py = time.time() - t0

# NumPy array
np_arr = np.arange(N)
t0 = time.time()
np_result = np_arr ** 2
t_np = time.time() - t0

print(f"Squaring {N:,} elements:")
print(f"  Python list : {t_py:.4f} sec")
print(f"  NumPy array : {t_np:.4f} sec")
print(f"  NumPy speedup: ~{t_py/t_np:.1f}x faster")

## Summary

| Feature | Function / Method |
|---|---|
| Create arrays | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()` |
| Inspect | `.shape`, `.ndim`, `.size`, `.dtype` |
| Reshape | `.reshape()`, `.flatten()`, `.T` |
| Stack | `np.vstack()`, `np.hstack()`, `np.concatenate()` |
| Math | `np.sin()`, `np.log()`, `np.exp()`, `np.sqrt()` |
| Stats | `np.mean()`, `np.std()`, `np.median()`, `np.min()`, `np.max()` |
| Linear Algebra | `np.dot()`, `np.linalg.inv()`, `np.linalg.eig()` |
| Random | `np.random.normal()`, `np.random.randint()`, `np.random.seed()` |

---
✅ **Lab 3 Complete**